name: PHPStan

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ master ]

jobs:
  phpstan:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest']
        php-versions: ['8.0', '8.1']
        phpunit-versions: ['latest']

    steps:

    - uses: actions/checkout@master

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse src/
